using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using NextGen.FiestaLib.Shn;

namespace NextGen.KingdomQuestTool
{
    internal static class Program
    {
        private static readonly string[] RequiredMainFiles =
        {
            "KingdomQuest.shn",
            "KingdomQuestMap.shn",
            "KingdomQuestRew.shn",
            "KQItem.shn",
        };

        private static readonly string[] PreferredFiles =
        {
            "KingdomQuest.shn",
            "KingdomQuestMap.shn",
            "KingdomQuestRew.shn",
            "KQItem.shn",
            "KQTeam.shn",
            "KQIsVote.shn",
            "KQVoteDesc.shn",
            "KQVoteMajorityRate.shn",
            "KingdomQuestDesc.shn",
        };

        private static int Main(string[] args)
        {
            if (args.Length < 3 || !args[0].Equals("--sql", StringComparison.OrdinalIgnoreCase))
            {
                Console.Error.WriteLine("Usage: NextGen.KingdomQuestTool --sql <output.sql> [--require-main] <source-directory-or-shn> [...]");
                return 2;
            }

            string output = args[1];
            bool requireMain = false;
            var inputs = new List<string>();
            for (int i = 2; i < args.Length; i++)
            {
                if (args[i].Equals("--require-main", StringComparison.OrdinalIgnoreCase))
                    requireMain = true;
                else
                    AddInput(args[i], inputs);
            }

            if (inputs.Count == 0)
            {
                Console.Error.WriteLine("No Kingdom Quest SHN sources found.");
                return 3;
            }

            var duplicateNames = inputs
                .GroupBy(path => Path.GetFileName(path), StringComparer.OrdinalIgnoreCase)
                .Where(group => group.Count() > 1)
                .ToList();
            if (duplicateNames.Count != 0)
            {
                foreach (var group in duplicateNames)
                {
                    Console.Error.WriteLine("Ambiguous KQ SHN source {0}:", group.Key);
                    foreach (string path in group.OrderBy(v => v, StringComparer.OrdinalIgnoreCase))
                        Console.Error.WriteLine("  {0}", path);
                }
                return 4;
            }

            if (requireMain)
            {
                var foundNames = new HashSet<string>(
                    inputs.Select(Path.GetFileName), StringComparer.OrdinalIgnoreCase);
                string[] missing = RequiredMainFiles.Where(name => !foundNames.Contains(name)).ToArray();
                if (missing.Length != 0)
                {
                    Console.Error.WriteLine("Missing required main KQ SHNs: {0}",
                        string.Join(", ", missing));
                    return 5;
                }
            }

            using (var writer = new StreamWriter(output, false, new UTF8Encoding(false)))
            {
                writer.WriteLine("-- Generated by NextGen.KingdomQuestTool from project-source SHN files.");
                writer.WriteLine("-- No primary key or gameplay semantics are guessed by this exporter.");
                writer.WriteLine();

                foreach (string path in inputs.OrderBy(p => p, StringComparer.OrdinalIgnoreCase))
                {
                    string sha256 = ComputeSha256(path);
                    Console.WriteLine("Reading {0} [sha256={1}]", path, sha256);
                    using (var table = new SHNFile(path))
                    {
                        Console.WriteLine("  records={0} columns={1}", table.Rows.Count, table.Columns.Count);
                        WriteTable(writer, table, Path.GetFileNameWithoutExtension(path), sha256);
                    }
                }
            }

            Console.WriteLine("Wrote {0}", output);
            return 0;
        }

        private static void AddInput(string input, IList<string> paths)
        {
            if (File.Exists(input))
            {
                if (input.EndsWith(".shn", StringComparison.OrdinalIgnoreCase) &&
                    !paths.Contains(input, StringComparer.OrdinalIgnoreCase))
                    paths.Add(input);
                return;
            }

            if (!Directory.Exists(input))
                return;

            foreach (string file in Directory.EnumerateFiles(input, "*.shn", SearchOption.AllDirectories))
            {
                string fileName = Path.GetFileName(file);
                if (PreferredFiles.Contains(fileName, StringComparer.OrdinalIgnoreCase) &&
                    !paths.Contains(file, StringComparer.OrdinalIgnoreCase))
                    paths.Add(file);
            }
        }

        private static void WriteTable(TextWriter writer, SHNFile table, string sourceName, string sha256)
        {
            string sqlName = "data_" + SanitizeIdentifier(sourceName).ToLowerInvariant();
            writer.WriteLine("-- Source: {0}; sha256={1}; records={2}; columns={3}",
                sourceName, sha256, table.Rows.Count, table.Columns.Count);
            writer.Write("-- Columns:");
            for (int i = 0; i < table.Columns.Count; i++)
            {
                var column = (ShnColumn)table.Columns[i];
                writer.Write(" {0}:{1}:{2}", column.ColumnName, column.TypeByte, column.Length);
            }
            writer.WriteLine();
            writer.WriteLine("DROP TABLE IF EXISTS `{0}`;", sqlName);
            writer.WriteLine("CREATE TABLE `{0}` (", sqlName);

            for (int i = 0; i < table.Columns.Count; i++)
            {
                var column = (ShnColumn)table.Columns[i];
                writer.Write("  `{0}` {1} NOT NULL", EscapeIdentifier(column.ColumnName), SqlType(column));
                writer.WriteLine(i + 1 == table.Columns.Count ? "" : ",");
            }
            writer.WriteLine(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");
            writer.WriteLine();

            if (table.Rows.Count != 0)
            {
                writer.Write("INSERT INTO `{0}` (", sqlName);
                for (int i = 0; i < table.Columns.Count; i++)
                {
                    if (i != 0) writer.Write(", ");
                    writer.Write("`{0}`", EscapeIdentifier(table.Columns[i].ColumnName));
                }
                writer.WriteLine(") VALUES");

                for (int r = 0; r < table.Rows.Count; r++)
                {
                    writer.Write("  (");
                    for (int c = 0; c < table.Columns.Count; c++)
                    {
                        if (c != 0) writer.Write(", ");
                        WriteValue(writer, table.Rows[r][c]);
                    }
                    writer.WriteLine(r + 1 == table.Rows.Count ? ");" : "),");
                }
            }
            writer.WriteLine();
        }

        private static string SqlType(ShnColumn column)
        {
            switch (column.TypeByte)
            {
                case 1:
                case 12:
                case 16:
                    return "TINYINT UNSIGNED";
                case 2:
                    return "SMALLINT UNSIGNED";
                case 3:
                case 11:
                case 18:
                case 27:
                    return "INT UNSIGNED";
                case 5:
                    return "FLOAT";
                case 13:
                case 21:
                    return "SMALLINT";
                case 20:
                    return "TINYINT";
                case 22:
                    return "INT";
                case 29:
                    return "BIGINT UNSIGNED";
                case 9:
                case 24:
                    return "VARCHAR(" + Math.Max(1, column.Length).ToString(CultureInfo.InvariantCulture) + ")";
                case 26:
                    return "TEXT";
                default:
                    throw new InvalidDataException("Unsupported SHN type " + column.TypeByte + " in column " + column.ColumnName);
            }
        }

        private static void WriteValue(TextWriter writer, object value)
        {
            if (value == null || value == DBNull.Value)
            {
                writer.Write("NULL");
                return;
            }

            if (value is string)
            {
                writer.Write("'");
                writer.Write(((string)value)
                    .Replace("\\", "\\\\")
                    .Replace("'", "\\'")
                    .Replace("\r", "\\r")
                    .Replace("\n", "\\n"));
                writer.Write("'");
                return;
            }

            if (value is float)
            {
                writer.Write(((float)value).ToString("R", CultureInfo.InvariantCulture));
                return;
            }

            writer.Write(Convert.ToString(value, CultureInfo.InvariantCulture));
        }

        private static string ComputeSha256(string path)
        {
            using (var stream = File.OpenRead(path))
            using (var sha = SHA256.Create())
            {
                byte[] hash = sha.ComputeHash(stream);
                var builder = new StringBuilder(hash.Length * 2);
                for (int i = 0; i < hash.Length; i++)
                    builder.Append(hash[i].ToString("x2", CultureInfo.InvariantCulture));
                return builder.ToString();
            }
        }

        private static string SanitizeIdentifier(string name)
        {
            var builder = new StringBuilder(name.Length);
            foreach (char ch in name)
                builder.Append(char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_');
            return builder.ToString();
        }

        private static string EscapeIdentifier(string name)
        {
            return name.Replace("`", "``");
        }
    }
}
