<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>NextGen.InterLib</RootNamespace>
    <AssemblyName>NextGen.InterLib</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NextGen.Util\NextGen.Util.csproj" />
  </ItemGroup>

</Project>
