-- Derived directly from the supplied QuestData.shn corpus.
-- Source SHA-256: 8c4ba17267967883169142c736e6d31d1a016c843d61411da7bca8dd244cc8b8
-- Source records: 2304
CREATE TABLE `quest_script_corpus_manifest` (`Opcode` VARCHAR(64) NOT NULL PRIMARY KEY, `Count` INT UNSIGNED NOT NULL);
INSERT INTO `quest_script_corpus_manifest` VALUES
('ACCEPT',2410),
('CANCEL',12),
('CREATE_ITEM',206),
('DELETE_ITEM',1474),
('DONE',2603),
('END',9446),
('GET_ITEM_LOT',104),
('GET_PLAYER_EMPTY_INVENTORY',676),
('GOTO',4),
('IF',3036),
('LINK',350),
('SAY',19924),
('SCENARIO',52),
('SET_ABSTATE',51);
-- Full lossless SQL conversion is generated by tools/import-questdata.py.
