#!/usr/bin/env python3
"""One-time QuestData.shn -> SQL importer.

QuestData.shn is a custom quest format, not a normal SHN table:
[4-byte signature][QUEST_DATA 0x2A8][Start][Doing][End]...
The three script lengths live at QUEST_DATA +0x294/+0x296/+0x298,
while the on-disk script order is Start, Doing, End. Runtime must never
read .shn; this tool exists only for the one-time SQL migration.
"""
import argparse
import re
import struct
from pathlib import Path

FIXED = 0x2A8
HEADER = 4
MAX_NPC = 5
MAX_ITEM = 5
MAX_REWARD = 12


def u8(b, o): return b[o]
def u16(b, o): return struct.unpack_from('<H', b, o)[0]
def u32(b, o): return struct.unpack_from('<I', b, o)[0]
def i32(b, o): return struct.unpack_from('<i', b, o)[0]
def i64(b, o): return struct.unpack_from('<q', b, o)[0]
def blob(b): return "X'" + b.hex() + "'"
def q(s): return "'" + s.replace('\\', '\\\\').replace("'", "''") + "'"


def script_text(raw):
    return raw.rstrip(b'\0').replace(b'\r\n', b'\n').replace(b'\r', b'\n').decode('utf-8', 'replace')


def first_say(s):
    m = re.search(r'(?mi)^\s*SAY\s+(\d+)\b', s)
    return int(m.group(1)) if m else 0


def parse(path):
    b = Path(path).read_bytes()
    pos = HEADER
    rows = []
    if len(b) < HEADER:
        raise ValueError('QuestData.shn is truncated')
    while pos + FIXED <= len(b):
        base = pos
        ss, se, sd = struct.unpack_from('<HHH', b, base + 0x294)
        sp = base + FIXED
        total = ss + sd + se
        if sp + total > len(b):
            raise ValueError(f'quest record at 0x{base:x} exceeds file')
        start = script_text(b[sp:sp + ss])
        doing = script_text(b[sp + ss:sp + ss + sd])
        end = script_text(b[sp + ss + sd:sp + total])
        rows.append((base, u32(b, base), u32(b, base + 4), ss, se, sd, start, doing, end))
        pos = sp + total
    if pos != len(b):
        raise ValueError(f'trailing bytes: {len(b) - pos}')
    return b, rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('input')
    ap.add_argument('-o', '--output', default='QuestData.sql')
    args = ap.parse_args()
    b, rows = parse(args.input)
    out = Path(args.output)
    with out.open('w', encoding='utf-8', newline='\n') as f:
        w = f.write
        w('-- Generated by tools/import-questdata.py from QuestData.shn.\n')
        w('-- One-time migration: original .shn is NOT required by emulator runtime.\n')
        w('SET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS=0;\n')
        for table in ['data_quest_start_dialog', 'data_quest_objective', 'data_quest_script', 'QuestData_Reward', 'QuestData_Item', 'QuestData_NPCMob', 'QuestData_ConditionEnd', 'QuestData_ConditionStart', 'QuestData']:
            w(f'DROP TABLE IF EXISTS `{table}`;\n')
        w('CREATE TABLE `QuestData` (`QuestID` INT UNSIGNED NOT NULL PRIMARY KEY, `SourceIndex` INT UNSIGNED NOT NULL, `Type` TINYINT UNSIGNED NOT NULL, `Repeatable` TINYINT UNSIGNED NOT NULL, `DailyQuestType` TINYINT UNSIGNED NOT NULL, `RawData` VARBINARY(680) NOT NULL, `ScriptStartSize` INT UNSIGNED NOT NULL, `ScriptEndSize` INT UNSIGNED NOT NULL, `ScriptDoingSize` INT UNSIGNED NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n')
        w('CREATE TABLE `QuestData_ConditionStart` (`QuestID` INT UNSIGNED NOT NULL PRIMARY KEY, `RawData` VARBINARY(64) NOT NULL, `bIsWaitListView` TINYINT UNSIGNED NOT NULL, `bIsWaitListProgress` TINYINT UNSIGNED NOT NULL, `bLevel` TINYINT UNSIGNED NOT NULL, `LevelMin` TINYINT UNSIGNED NOT NULL, `LevelMax` TINYINT UNSIGNED NOT NULL, `bNPC` TINYINT UNSIGNED NOT NULL, `NPCID` INT UNSIGNED NOT NULL, `bItem` TINYINT UNSIGNED NOT NULL, `ItemID` INT UNSIGNED NOT NULL, `ItemLot` INT UNSIGNED NOT NULL, `bLocation` TINYINT UNSIGNED NOT NULL, `LocationRaw` VARBINARY(18) NOT NULL, `LocationMap` INT UNSIGNED NOT NULL, `LocationX` INT NOT NULL, `LocationY` INT NOT NULL, `LocationRange` INT UNSIGNED NOT NULL, `bQuest` TINYINT UNSIGNED NOT NULL, `QuestPrerequisiteID` INT UNSIGNED NOT NULL, `bRace` TINYINT UNSIGNED NOT NULL, `Race` TINYINT UNSIGNED NOT NULL, `bClass` TINYINT UNSIGNED NOT NULL, `Class` TINYINT UNSIGNED NOT NULL, `bGender` TINYINT UNSIGNED NOT NULL, `Gender` TINYINT UNSIGNED NOT NULL, `bDate` TINYINT UNSIGNED NOT NULL, `DateMode` TINYINT UNSIGNED NOT NULL, `DateRaw` VARBINARY(16) NOT NULL, `DateStart` BIGINT NOT NULL, `DateEnd` BIGINT NOT NULL, KEY `idx_qs_npc` (`NPCID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n')
        w('CREATE TABLE `QuestData_ConditionEnd` (`QuestID` INT UNSIGNED NOT NULL PRIMARY KEY, `RawData` VARBINARY(104) NOT NULL, `bIsWaitListProgress` TINYINT UNSIGNED NOT NULL, `bLevel` TINYINT UNSIGNED NOT NULL, `Level` TINYINT UNSIGNED NOT NULL, `bLocation` TINYINT UNSIGNED NOT NULL, `LocationRaw` VARBINARY(18) NOT NULL, `LocationMap` INT UNSIGNED NOT NULL, `LocationX` INT NOT NULL, `LocationY` INT NOT NULL, `LocationRange` INT UNSIGNED NOT NULL, `bScenario` TINYINT UNSIGNED NOT NULL, `ScenarioID` INT UNSIGNED NOT NULL, `bRace` TINYINT UNSIGNED NOT NULL, `Race` TINYINT UNSIGNED NOT NULL, `bClass` TINYINT UNSIGNED NOT NULL, `Class` TINYINT UNSIGNED NOT NULL, `bTimeLimit` TINYINT UNSIGNED NOT NULL, `TimeLimit` INT UNSIGNED NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n')
        w('CREATE TABLE `QuestData_NPCMob` (`QuestID` INT UNSIGNED NOT NULL, `Slot` TINYINT UNSIGNED NOT NULL, `bNPCMob` TINYINT UNSIGNED NOT NULL, `NPCMobID` INT UNSIGNED NOT NULL, `NPCMobAction` TINYINT UNSIGNED NOT NULL, `NPCMobCount` INT UNSIGNED NOT NULL, `TargetGroup` INT UNSIGNED NOT NULL, PRIMARY KEY (`QuestID`,`Slot`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n')
        w('CREATE TABLE `QuestData_Item` (`QuestID` INT UNSIGNED NOT NULL, `Slot` TINYINT UNSIGNED NOT NULL, `bItem` TINYINT UNSIGNED NOT NULL, `ItemID` INT UNSIGNED NOT NULL, `ItemLot` INT UNSIGNED NOT NULL, PRIMARY KEY (`QuestID`,`Slot`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n')
        w('CREATE TABLE `QuestData_Reward` (`QuestID` INT UNSIGNED NOT NULL, `Slot` TINYINT UNSIGNED NOT NULL, `UseType` TINYINT UNSIGNED NOT NULL, `RewardType` TINYINT UNSIGNED NOT NULL, `Value1` INT UNSIGNED NOT NULL, `Value2` INT UNSIGNED NOT NULL, `RawData` VARBINARY(12) NOT NULL, PRIMARY KEY (`QuestID`,`Slot`), KEY `idx_qr_use` (`QuestID`,`UseType`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n')
        w('CREATE TABLE `data_quest_script` (`QuestID` INT UNSIGNED NOT NULL PRIMARY KEY, `StartScript` LONGTEXT NOT NULL, `ActionScript` LONGTEXT NOT NULL, `FinishScript` LONGTEXT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n')
        w('CREATE TABLE `data_quest_start_dialog` (`QuestID` INT UNSIGNED NOT NULL PRIMARY KEY, `DialogID` INT UNSIGNED NOT NULL, KEY `idx_qsd_dialog` (`DialogID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n')
        w('CREATE VIEW `data_quest` AS SELECT q.QuestID,q.SourceIndex,q.Type,q.Repeatable,s.NPCID AS StartingNpc,s.ItemID AS StartingItemID,s.ItemLot AS StartingItemLot,s.QuestPrerequisiteID AS StartingQuestID FROM QuestData q INNER JOIN QuestData_ConditionStart s ON s.QuestID=q.QuestID;\n')
        w('CREATE VIEW `data_quest_objective` AS SELECT QuestID,Slot,NPCMobID AS TargetID,NPCMobCount AS Amount,1 AS IsMob,1 AS HasToBeKilled,1 AS Active FROM QuestData_NPCMob WHERE bNPCMob=1 AND NPCMobAction=1;\n')
        for base, idx, qid, ss, se, sd, start, doing, end in rows:
            fixed = b[base:base + FIXED]
            st = b[base + 0x18:base + 0x58]
            en = b[base + 0x58:base + 0xc0]
            w(f'INSERT INTO QuestData VALUES ({qid},{idx},{u8(fixed,0x11)},{u8(fixed,0x12)},{u8(fixed,0x13)},{blob(fixed)},{ss},{se},{sd});\n')
            w(f'INSERT INTO QuestData_ConditionStart VALUES ({qid},{blob(st)},{u8(st,0)},{u8(st,1)},{u8(st,2)},{u8(st,3)},{u8(st,4)},{u8(st,5)},{u16(st,6)},{u8(st,8)},{u16(st,10)},{u16(st,12)},{u8(st,14)},{blob(st[14:32])},{u16(st,16)},{i32(st,20)},{i32(st,24)},{u32(st,28)},{u8(st,32)},{u16(st,34)},{u8(st,36)},{u8(st,37)},{u8(st,38)},{u8(st,39)},{u8(st,40)},{u8(st,41)},{u8(st,42)},{u8(st,43)},{blob(st[48:64])},{i64(st,48)},{i64(st,56)});\n')
            w(f'INSERT INTO QuestData_ConditionEnd VALUES ({qid},{blob(en)},{u8(en,0)},{u8(en,1)},{u8(en,2)},{u8(en,0x4a)},{blob(en[0x4a:0x5c])},{u16(en,0x4c)},{i32(en,0x50)},{i32(en,0x54)},{u32(en,0x58)},{u8(en,0x5c)},{u16(en,0x5e)},{u8(en,0x60)},{u8(en,0x61)},{u8(en,0x62)},{u8(en,0x63)},{u8(en,0x64)},{u16(en,0x66)});\n')
            for slot in range(MAX_NPC):
                o = base + 0x5c + slot * 8
                w(f'INSERT INTO QuestData_NPCMob VALUES ({qid},{slot},{u8(b,o)},{u16(b,o+2)},{u8(b,o+4)},{u8(b,o+5)},{u16(b,o+6)});\n')
            for slot in range(MAX_ITEM):
                o = base + 0x84 + slot * 6
                w(f'INSERT INTO QuestData_Item VALUES ({qid},{slot},{u8(b,o)},{u16(b,o+2)},{u16(b,o+4)});\n')
            for slot in range(MAX_REWARD):
                o = base + 0x204 + slot * 12
                w(f'INSERT INTO QuestData_Reward VALUES ({qid},{slot},{u8(b,o)},{u8(b,o+1)},{u32(b,o+4)},{u32(b,o+8)},{blob(b[o:o+12])});\n')
            w(f'INSERT INTO data_quest_script VALUES ({qid},{q(start)},{q(doing)},{q(end)});\n')
            sid = first_say(start)
            if sid:
                w(f'INSERT INTO data_quest_start_dialog VALUES ({qid},{sid});\n')
        w('SET FOREIGN_KEY_CHECKS=1;\n')
    print(f'parsed {len(rows)} QuestData records; wrote {out} ({out.stat().st_size} bytes)')


if __name__ == '__main__':
    main()
